lexik_jwt_authentication:
    secret_key: "%kernel.project_dir%/config/jwt/private.pem" # Le chemin vers clé privée
    public_key: "%kernel.project_dir%/config/jwt/public.pem" # Le chemin vers clé publique
    pass_phrase: "brunosport" # La phrase secrète  lors de la génération des clés
    token_ttl: 3600 # Durée de vie du token en secondes (ici, 1 heure)
