security:
    enable_authenticator_manager: true

    # Définir le hasher pour les mots de passe
    password_hashers:
        App\Entity\User:
            algorithm: bcrypt

    # Définir les fournisseurs de l'utilisateur
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    # Configurer les firewalls
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/api/login
            stateless: true
            json_login:
                check_path: /api/login_check
                success_handler: App\EventListener\AuthenticationSuccessListener # Ici, vous spécifiez votre service personnalisé
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern: ^/api
            stateless: true
            jwt: ~

        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_security_login
                check_path: app_security_login
                default_target_path: admin
            logout:
                path: app_security_logout
                target: /

    # Contrôle d'accès pour définir les autorisations basées sur les routes
    access_control:
        # Autoriser l'accès anonyme à l'API de connexion et d'inscription
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/users/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }

        # Seul l'administrateur peut accéder aux sondages via l'API
        - { path: ^/api/polls, roles: [ROLE_ADMIN, ROLE_USER] }

        # Seul un utilisateur authentifié peut accéder à l'API
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }

        # Seul l'administrateur peut accéder au tableau de bord
        - { path: ^/admin, roles: ROLE_ADMIN }

when@test:
    security:
        password_hashers:
            App\Entity\User:
                algorithm: bcrypt
                cost: 4
